### ISSUE TITLE
Add unity

### ISSUE THREAD

**Issue by HafizZiq** [Magisk-Modules-Repo/ASUS-Style-Suite#3]
make it easier for install and uninstall if someone had bootloop or etc,they can uninstall via recovery

**Comment by xerta555** [comment]
> make it easier for install and uninstall if someone had bootloop or etc,they can uninstall via recovery

As the module is very simple and don't make any complicated things, the mm module is updated for Magisk v19 as other similary module for managing Magisk modules in a custom recoveries, there is no need to merge this module to the Unity model.
